### ISSUE TITLE
Add icon to map

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#11]
The map looks it would benefit from a pointer/icon adding to it. (low priority with @mikelmaron able to assist if needed).

**Comment by frafra** [comment]
👍

**Comment by frafra** [comment]
Marker added (I also updated mapbox and changed a couple of js lines in order to make everything works with the new version).

There are two defects at the moment:
- The default marker is white: it is not very easy to spot on a light gray/white map
- Markers are centered by default (they are not anchored at their bottoms)

**Comment by frafra** [comment]
I tried to use our logo to create a custom marker.
