### ISSUE TITLE
favicon has yellow border in browser

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2018#18]
![screen shot 2018-01-08 at 3 18 20 pm](https://user-images.githubusercontent.com/22896/34690461-407f7e48-f487-11e7-949b-82e221ff1644.png)

on chrome on iOS the favicon has yellow-ish border, rather than red ... looks like 🇧🇷  ;)

**Comment by frafra** [comment]
Uhm, this could be due to the fact that logo resolution is scaled-down and the red border blends with the white around it... That's tricky to solve. If we disable anti-aliasing we would respect the colors, but it would looks blocky; otherwise we could remove the outer white border, but that would be a quite important change to the logo.

**Comment by althio** [comment]
I tried with thick red border and got this: ![favicon-16x16](https://user-images.githubusercontent.com/9863567/34692728-63fd4e24-f4c1-11e7-9a13-b4d48d47b0f5.png)

**Comment by frafra** [comment]
@althio This one looks better, I will generate the new low-res favicons with this little modifications if everybody is fine with that.
